print ("wiggle")
print (" wiggle")
print ("  wiggle")
print ("   wiggle")
print ("    wiggle")
print ("     wiggle")
print ("    wiggle")
print ("   wiggle")
print ("   wiggle")
print ("  wiggle")
print (" wiggle")
print ("wiggle")
print (" wiggle")
print ("wiggle")
print (" wiggle")
print ("  wiggle")
print ("   wiggle")
print ("    wiggle")
print ("     wiggle")
print ("    wiggle")
print ("   wiggle")
print ("   wiggle")
print ("  wiggle")
print (" wiggle")
print ("wiggle")
print (" wiggle")
print ("wiggle")
print (" wiggle")
print ("  wiggle")
print ("   wiggle")
print ("    wiggle")
print ("     wiggle")
print ("    wiggle")
print ("   wiggle")
print ("   wiggle")
print ("  wiggle")
print (" wiggle")
print ("wiggle")
print (" wiggle")
print ("wiggle")
print (" wiggle")
print ("  wiggle")
print ("   wiggle")
print ("    wiggle")
print ("     wiggle")
print ("    wiggle")
print ("   wiggle")
print ("   wiggle")
print ("  wiggle")
print (" wiggle")
print ("wiggle")
print (" wiggle")
print ("wiggle")
print (" wiggle")
print ("  wiggle")
print ("   wiggle")
print ("    wiggle")
print ("     wiggle")
print ("    wiggle")
print ("   wiggle")
print ("   wiggle")
print ("  wiggle")
print (" wiggle")
print ("wiggle")
print (" wiggle")
print ("wiggle")
print (" wiggle")
print ("  wiggle")
print ("   wiggle")
print ("    wiggle")
print ("     wiggle")
print ("    wiggle")
print ("   wiggle")
print ("   wiggle")
print ("  wiggle")
print (" wiggle")
print ("wiggle")
print (" wiggle")
print ("wiggle")
print (" wiggle")
print ("  wiggle")
print ("   wiggle")
print ("    wiggle")
print ("     wiggle")
print ("    wiggle")
print ("   wiggle")
print ("   wiggle")
print ("  wiggle")
print (" wiggle")
print ("wiggle")
print (" wiggle")
print ("wiggle")
print (" wiggle")
print ("  wiggle")
print ("   wiggle")
print ("    wiggle")
print ("     wiggle")
print ("    wiggle")
print ("   wiggle")
print ("   wiggle")
print ("  wiggle")
print (" wiggle")
print ("wiggle")
print (" wiggle")
print ("wiggle")
print (" wiggle")
print ("  wiggle")
print ("   wiggle")
print ("    wiggle")
print ("     wiggle")
print ("    wiggle")
print ("   wiggle")
print ("   wiggle")
print ("  wiggle")
print (" wiggle")
print ("wiggle")
print (" wiggle")
print ("wiggle")
print (" wiggle")
print ("  wiggle")
print ("   wiggle")
print ("    wiggle")
print ("     wiggle")
print ("    wiggle")
print ("   wiggle")
print ("   wiggle")
print ("  wiggle")
print (" wiggle")
print ("wiggle")
print (" wiggle")
print ("wiggle")
print (" wiggle")
print ("  wiggle")
print ("   wiggle")
print ("    wiggle")
print ("     wiggle")
print ("    wiggle")
print ("   wiggle")
print ("   wiggle")
print ("  wiggle")
print (" wiggle")
print ("wiggle")
print (" wiggle")
print ("wiggle")
print (" wiggle")
print ("  wiggle")
print ("   wiggle")
print ("    wiggle")
print ("     wiggle")
print ("    wiggle")
print ("   wiggle")
print ("   wiggle")
print ("  wiggle")
print (" wiggle")
print ("wiggle")
print (" wiggle")
print ("wiggle")
print (" wiggle")
print ("  wiggle")
print ("   wiggle")
print ("    wiggle")
print ("     wiggle")
print ("    wiggle")
print ("   wiggle")
print ("   wiggle")
print ("  wiggle")
print (" wiggle")
print ("wiggle")
print (" wiggle")
print ("wiggle")
print (" wiggle")
print ("  wiggle")
print ("   wiggle")
print ("    wiggle")
print ("     wiggle")
print ("    wiggle")
print ("   wiggle")
print ("   wiggle")
print ("  wiggle")
print (" wiggle")
print ("wiggle")
print (" wiggle")
print ("wiggle")
print (" wiggle")
print ("  wiggle")
print ("   wiggle")
print ("    wiggle")
print ("     wiggle")
print ("    wiggle")
print ("   wiggle")
print ("   wiggle")
print ("  wiggle")
print (" wiggle")
print ("wiggle")
print (" wiggle")
print ("wiggle")
print (" wiggle")
print ("  wiggle")
print ("   wiggle")
print ("    wiggle")
print ("     wiggle")
print ("    wiggle")
print ("   wiggle")
print ("   wiggle")
print ("  wiggle")
print (" wiggle")
print ("wiggle")
print (" wiggle")
print ("wiggle")
print (" wiggle")
print ("  wiggle")
print ("   wiggle")
print ("    wiggle")
print ("     wiggle")
print ("    wiggle")
print ("   wiggle")
print ("   wiggle")
print ("  wiggle")
print (" wiggle")
print ("wiggle")
print (" wiggle")
print ("wiggle")
print (" wiggle")
print ("  wiggle")
print ("   wiggle")
print ("    wiggle")
print ("     wiggle")
print ("    wiggle")
print ("   wiggle")
print ("   wiggle")
print ("  wiggle")
print (" wiggle")
print ("wiggle")
print (" wiggle")
print ("wiggle")
print (" wiggle")
print ("  wiggle")
print ("   wiggle")
print ("    wiggle")
print ("     wiggle")
print ("    wiggle")
print ("   wiggle")
print ("   wiggle")
print ("  wiggle")
print (" wiggle")
print ("wiggle")
print (" wiggle")
print ("wiggle")
print (" wiggle")
print ("  wiggle")
print ("   wiggle")
print ("    wiggle")
print ("     wiggle")
print ("    wiggle")
print ("   wiggle")
print ("   wiggle")
print ("  wiggle")
print (" wiggle")
print ("wiggle")
print (" wiggle")
print ("wiggle")
print (" wiggle")
print ("  wiggle")
print ("   wiggle")
print ("    wiggle")
print ("     wiggle")
print ("    wiggle")
print ("   wiggle")
print ("   wiggle")
print ("  wiggle")
print (" wiggle")
print ("wiggle")
print (" wiggle")
print ("wiggle")
print (" wiggle")
print ("  wiggle")
print ("   wiggle")
print ("    wiggle")
print ("     wiggle")
print ("    wiggle")
print ("   wiggle")
print ("   wiggle")
print ("  wiggle")
print (" wiggle")
print ("wiggle")
print (" wiggle")
print ("wiggle")
print (" wiggle")
print ("  wiggle")
print ("   wiggle")
print ("    wiggle")
print ("     wiggle")
print ("    wiggle")
print ("   wiggle")
print ("   wiggle")
print ("  wiggle")
print (" wiggle")
print ("wiggle")
print (" wiggle")
print ("wiggle")
print (" wiggle")
print ("  wiggle")
print ("   wiggle")
print ("    wiggle")
print ("     wiggle")
print ("    wiggle")
print ("   wiggle")
print ("   wiggle")
print ("  wiggle")
print (" wiggle")
print ("wiggle")
print (" wiggle")
print ("wiggle")
print (" wiggle")
print ("  wiggle")
print ("   wiggle")
print ("    wiggle")
print ("     wiggle")
print ("    wiggle")
print ("   wiggle")
print ("   wiggle")
print ("  wiggle")
print (" wiggle")
print ("wiggle")
print (" wiggle")
print ("wiggle")
print (" wiggle")
print ("  wiggle")
print ("   wiggle")
print ("    wiggle")
print ("     wiggle")
print ("    wiggle")
print ("   wiggle")
print ("   wiggle")
print ("  wiggle")
print (" wiggle")
print ("wiggle")
print (" wiggle")
print ("wiggle")
print (" wiggle")
print ("  wiggle")
print ("   wiggle")
print ("    wiggle")
print ("     wiggle")
print ("    wiggle")
print ("   wiggle")
print ("   wiggle")
print ("  wiggle")
print (" wiggle")
print ("wiggle")
print (" wiggle")
print ("wiggle")
print (" wiggle")
print ("  wiggle")
print ("   wiggle")
print ("    wiggle")
print ("     wiggle")
print ("    wiggle")
print ("   wiggle")
print ("   wiggle")
print ("  wiggle")
print (" wiggle")
print ("wiggle")
print (" wiggle")
